apiVersion: policy.open-cluster-management.io/v1
kind: IamPolicy
metadata:
  name: iam-policy-example
  label:
    category: "System-Integrity"
spec:
  #Include are the namespaces for which you want to watch cluster administrator role and IAM rolebinings, while exclude are the namespaces you explicitly do not want to watch
  namespaceSelector:
    include: ["default","kube-*"]
    exclude: ["kube-system"]
  #labelSelector:
    #env: "production"
  remediationAction: inform # enforce or inform
  severity: medium
  maxClusterRoleBindingUsers: 5
  maxRoleBindingViolationsPerNamespace: 2
